config/routes.rb
Blog::Application.routes.draw do
  

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  devise_for :owners
  root 'petar#home'
  get "front_end/rindex"
  resources :venues
  resources :posts

  

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :restaurant
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def sign_up
    default_params.permit(:name, :email)
  end
  has_many :venues
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_one :address
	mount_uploader :image, ImageUploader
	belongs_to :owner
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :owner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  private
  def currentfb_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :currentfb_user

  client = Twitter::Streaming::Client.new do |config|
    config.consumer_key        = "YOUR_CONSUMER_KEY"
    config.consumer_secret     = "YOUR_CONSUMER_SECRET"
    config.access_token        = "YOUR_ACCESS_TOKEN"
    config.access_token_secret = "YOUR_ACCESS_SECRET"
  end
  

end

app/controllers/front_end_controller.rb
class FrontEndController < ApplicationController
  def rindex
  end
end

app/controllers/petar_controller.rb
class PetarController < ApplicationController
  layout "petar"
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end


	def new
		@post = Post.new
	end

	def create
	  @post = Post.new(params[:post].permit(:title, :text))
	 
	  if @post.save
	  	redirect_to @post
	  else
	  	render 'new'
	  end	
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :text))
			redirect_to @post
		else 
			render 'edit'
		end
	end

	def dstroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end



	def show
		@post = Post.find(params[:id])
	end

 
private
	  def post_params
	    params.require(:post).permit(:title, :text)
	  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_owner!, only: [:new, :create, :edit, :update, :destroy]
  before_action :confirm_ownership, only: [:edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_owner.restaurants.build(restaurant_params)
    if @restaurant.save
      redirect_to root_url, notice: "#{@restaurant.name} was successfully created!"
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = @restaurant.reservations.build
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to root_url, notice: "#{@restaurant.name} was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to root_url, alert: "#{@restaurant.name} was successfully deleted!"
  end

private
  
  def restaurant_params
    params.require(:restaurant).permit(:owner_id, :name, :description, :address, :phone_number, :image, :menu)
  end

  def confirm_ownership
    restaurant = Restaurant.find(params[:id])
    if restaurant.owner != current_owner
      redirect_to :show, notice: "You don't own this restaurant!"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
	before_action :authenticate_owner!, only: [:new, :create, :edit, :update, :destroy]

	def index
		@venues = Venue.all
	end

	def new
		@venue = Venue.new
	end

	def create
		@venue = current_owner.venues.build(venue_params)
		if @venue.save
			redirect_to root_url, notice: "#{@venue.name} was successfully created!"
		else
			render :new
		end
	end

	def show
		@venue = Venue.find(params[:id])
		#@resrv = @venue.reservations.build
	end

	def edit
		@venue = Venue.find(params[:id])
	end

	def update		
		@venue = Venue.find(params[:id])
		if @venue.update(venue_params)
		  redirect_to root_url, notice: "#{@venue.name} was successfully updated!"
		else
		  render :edit
		end
	end

	def destroy
	  @venue = Venue.find(params[:id])
	  @venue.destroy
	  redirect_to root_url, alert: "#{@venue.name} was successfully deleted!"
	end

	private

		def venue_params
		  params.require(:venue).permit(:owner_id, :name, :description, :address, :phone, :image)
		end

end

app/helpers/front_end_helper.rb
module FrontEndHelper
end

app/helpers/petar_helper.rb
module PetarHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/front_end/rindex.haml
.row
  .large-12.columns
    .panel
      %h1 Food Near You
/ End Header and Nav
.row
  .large-9.columns
    / Feed Entry
    .row
      .large-2.columns.small-3
        %img{src: "http://placehold.it/80x80&text=[img]"}/
      .large-10.columns
        %p
          %strong Tria
          %br
          Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. 
          %br
          %a{href: ""} Eat Here
            
    / End Feed Entry
    %hr/
    / Feed Entry
    .row
      .large-2.columns.small-3
        %img{src: "http://placehold.it/80x80&text=[img]"}/
      .large-10.columns
        %p
          %strong Some Person said:
          Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong.
        %ul.inline-list
          %li
            %a{href: ""} Reply
          %li
            %a{href: ""} Share
        %h6 2 Comments
        .row
          .large-2.columns.small-3
            %img{src: "http://placehold.it/50x50&text=[img]"}/
          .large-10.columns
            %p Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit
    / End Feed Entry
  / Right Sidebar
  / On small devices this column is hidden
  %aside.large-3.columns.hide-for-small
    %p
      %img{src: "http://placehold.it/300x440&text=[ad]"}/
    %p
      %img{src: "http://placehold.it/300x440&text=[ad]"}/

app/views/home/home.html.erb
<div class="container">
  <div class="container-inner">
    <h1><h2>{ entrepreneur + full stack developer }</h2> <h1><span>Petar Ivacic</span> </h1>
    <nav>
      <ul>
        <li><a href="#">L</a></li>
        <li><a href="#">T</a></li>
        <li><a href="#">f</a></li>
        <li><a href="#">s</a></li>
        <li><a href="#">g</a></li>
      </ul>
    </nav>
  </div>
</div>

app/views/home/resume.haml
- provide(:title, 'CV/Resume')
.row
  .large-12.columns
    %hr
.row
  .large-4.columns
    %h3 Petar Ivacic
  .large-8.columns
    %h5.subheader
      Entrepreneur, Engineer, Developer. Passionate about rowing and Ruby Rails framework.
.row
  .large-12.columns
    %hr
.row
  .large-4.columns
    %h6.subheader 10/13 - Present
  .large-8.columns
    %h5 Startup Institute
    %p 
      Immersive 8-week professional accelerator to gain the skills necessary to be a valuable and results producing employee at a startup company.     
.row
  .large-12.columns
    %hr
.row
  .large-4.columns
    %h6.subheader 10/13 - Present
  .large-8.columns
    %h5 Frabbit
    %p 
      The first social network that will inspire and motivate you to reach your true fitness potential.   

.row
  .large-12.columns
    %hr
.row
  .large-4.columns
    %h6.subheader 09/04 - 12/12
  .large-8.columns
    %h5 RowZone
    %p 
      The World's First Indoor Rowing Fitness Franchise. 
.row
  .large-12.columns
    %hr
  .row
  .large-4.columns
    %h6.subheader 07/11 - 02/12
  .large-8.columns
    %h5 Doozer Construction
    %p 
      A full service Construction Management and General Contracting company based in Philadelphia, PA     
.row
  .large-12.columns
    %hr
  .row
  .large-4.columns
    %h6.subheader 08/12 - 12/12
  .large-8.columns
    %h5 Barilotti Wealth Strategies
    %p 
          
.row
  .large-12.columns
    %hr

app/views/layouts/_footer.haml
/ Footer
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p © Petar Ivacic. SINY 2013.
      .large-6.columns
        %ul.inline-list.right
          %li
            %a{href: "#"} About
          %li
            %a{href: "#"} Link 2
          %li
            %a{href: "#"} Link 3
          %li
            %a{href: "#"} Link 4

app/views/layouts/_nav.haml
%nav.top-bar{"data-options" => "is_hover:false"}
  %ul.title-area
    %li.name
      %h1
        %a{href: "#"}
          Resrv.me
  %section.top-bar-section
    %ul.right
      - if owner_signed_in? 
        %li.has-dropdown
          %a= link_to current_owner.email, '#'
          %ul.dropdown
            %li
              %a= link_to 'Account', new_venue_path
              %a= link_to 'Logout', destroy_owner_session_path(owner_session), method: :delete
      - else
        %li
          %a= link_to 'Log In', new_owner_session_path
        %li
          %a= link_to 'Sign Up', new_owner_registration_path


 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 pp
]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class='row'>
      <div class="large-12 columns">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
      <!--
      <div class="large-4 columns">
        <h2>The Side Bar</h2>
      </div>
      -->
    </div>
    <%= render 'layouts/footer' %>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/petar.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 pp
]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=320, initial-scale=1">

    <title>Petar Ivacic</title>

    <%= stylesheet_link_tag  "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <%= yield %>
  </body>
</html>

app/views/petar/home.html.erb
<style>
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300);
@import url(http://weloveiconfonts.com/api/?family=zocial);
::selection {
  background-color: #b3d4fc; }

::-moz-selection {
  background-color: #b3d4fc; }

body {
  background-color: #FFF;
  font-family: "Source Sans Pro", sans-serif;
  font-size: 16px;
  text-align: center;
  color: #666; }

.container {
  position: fixed;
  width: 100%;
  height: 100%;
  display: table; 
padding-bottom: 60px;
padding-top: 60px;}

.container-inner {
  display: table-cell;

   }

h1 {
  margin-bottom: 0em;
  padding-bottom: 0px;
  text-align: center;
  font-size: 58px;
  font-weight: 600;
  letter-spacing: 0.1618em; }
  h1:hover {
    cursor: default; }
  h1 span {
    color: #f38434; }

h5 {
  padding-top: 0px;
  text-align: center;
  font-size: 16px;
  font-weight: 100;
  font-color: #666;
  letter-spacing: 0.2818em; }
  h5:hover {
    cursor: default; }
  h5 span {
    color: #2ecc71; }

nav {
  text-align: center; }

ul, li, a {
  display: inline-block;
  padding-left: 0px; }

li {
  padding: 5px 5px 5px 5px; }
  li:last-child {
    border-right-color: transparent; }

a {
  width: 54px;
  height: 54px;
  line-height: 54px;
  text-decoration: none;
  color: #111;
  font-family: "zocial", sans-serif;
  font-size: 28px;
  /*  @include transition(background-color .15s ease-in-out);*/ }
  a:hover {
    color: #f38434; }
    </style>

<div class="container">
<div class="container-inner">
  <div class="row">
  <div class="large-12 columns">
    <h1><span>Petar Ivacic</span> </h1>
    </div></div>
      <div class="row">
  <div class="large-12 columns">
    <h5 class="text-center">{entrepreneur + full stack developer}</h5>
    </div></div>
          <div class="row">
  <div class="large-12 columns">
      <ul class="text-center">
        <li><a href="http://linkedin.com/in/petarivacic">L</a></li>
        <li><a href="http://twitter.com/petarivacic">T</a></li>
        <li><a href="http://facebook.com/petarivacic">f</a></li>
        <li><a href="http://soundcloud.com/petar-ivacic">s</a></li>
        <li><a href="http://github.com/petarivacic">g</a></li>
      </ul>
      </div></div>
      </div>
      </div>

app/views/posts/_post.haml
%article
  %h3

app/views/posts/_sidebar.haml
%h5 Categories
%ul.side-nav
  %li
    %a{href: "#"} News
  %li
    %a{href: "#"} Code
  %li
    %a{href: "#"} Design
  %li
    %a{href: "#"} Fun
  %li
    %a{href: "#"} Weasels
.panel
  %h5 Featured
  %p Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.
  %a{href: "#"} Read More →
  / End Sidebar

app/views/posts/index.haml
.row
	.large-12.columns
		%h1 
			Blog
    	%small This is my blog. 
    %hr
.row
  .large-9.columns{role: "content"}
		= render @posts
/ End Main Content and Sidebar

app/views/posts/new.haml
= form_for :post, url: posts_path do |f|
  - if @post.errors.any?
    #errorExplanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited
        this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br/
    = f.text_field :title
  %p
    = f.label :text
    %br/
    = f.text_area :text
  %p
    = f.submit
= link_to 'Back', posts_path

app/views/posts/show.haml
%p
	%strong Text:
	= @post.title
%p
	%strong Text:
	= @post.text

= link_to 'Edit', edit_post_path(@post)
= link_to 'Back', posts_path

app/views/venues/_restaurant.haml
.row
  .large-2.columns.small-3
    %img{src: "http://placehold.it/80x80&text=[img]"}/
  .large-10.columns
    %p
      %strong= venue.name
      %br
      = venue.description 
      %br
      %a{href: ""} Eat Here
      %hr
        

app/views/venues/_venue.haml
.row
  .large-2.columns.small-3
    %img{src: "http://placehold.it/80x80&text=[img]"}/
  .large-10.columns
    %p
      %strong= venue.name
      %br
      = venue.description 
      %br
      %a{href: ""} Eat Here
      %hr
        

app/views/venues/index.haml
.row
	.large-12.columns
		%h3 All Venues
		%hr
.row
	.large-12.columns
		= render @venues
#user-widget
	- if currentfb_user
		= succeed "!" do
			%strong= currentfb_user.name
			= link_to "Sign out", signout_path, id: "sign_out"
	- else
		= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in"

app/views/venues/new.haml
.row
  %h2 Add New Venue
  .large-6.columns
    = form_for :venue, url: venues_path, :html => {:multipart => true} do |f|
      - if @venue.errors.any?
        #errorExplanation
          %h2
            = pluralize(@venue.errors.count, "error")
            prohibited
            this post from being saved:
          %ul
            - @venue.errors.full_messages.each do |msg|
              %li= msg
      %p
        = f.label :name
        = f.text_field :name
      %p
        = f.label :description
        = f.text_area :description
      %p
        = f.file_field :image
      %p
        = f.submit
    = link_to 'Back', venues_path

app/views/venues/show.haml
.row
  .large-9.columns
    %h3= @venue.name
    %p= @venue.description
    .section-container.tabs{"data-section" => ""}
      %section.section
        %h5.title
          %a{href: "#panel1"} About
        .content{"data-slug" => "panel1"}
          %form
            .row.collapse
              .large-2.columns
                %label.inline Your Name
              .large-10.columns
                %input#yourName{placeholder: "Jane Smith", type: "text"}/
            .row.collapse
              .large-2.columns
                %label.inline Your Email
              .large-10.columns
                %input#yourEmail{placeholder: "jane@smithco.com", type: "text"}/
            %label Leave a tip for others...
            %textarea{rows: "4"}
            %button.radius.button{type: "submit"} Submit
      %section.section
        %h5.title
          %a{href: "#panel2"} Instructors
        .content{"data-slug" => "panel2"}
          %ul.large-block-grid-5
            %li
              %a{href: "mailto:mal@serenity.bc.reb"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                Mal Reynolds
            %li
              %a{href: "mailto:zoe@serenity.bc.reb"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                Zoe Washburne
            %li
              %a{href: "mailto:jayne@serenity.bc.reb"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                Jayne Cobb
            %li
              %a{href: "mailto:doc@serenity.bc.reb"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                Simon Tam
            %li
              %a{href: "mailto:killyouwithmymind@serenity.bc.reb"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                River Tam
            %li
              %a{href: "mailto:leafonthewind@serenity.bc.reb"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                Hoban Washburne
            %li
              %a{href: "mailto:book@serenity.bc.reb"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                Shepherd Book
            %li
              %a{href: "mailto:klee@serenity.bc.reb"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                Kaywinnet Lee Fry
            %li
              %a{href: "mailto:inara@guild.comp.all"}
                %img{src: "http://placehold.it/200x200&text=[person]"}>/
                Inarra Serra
  / End Contact Details
  / Sidebar
  .large-3.columns
    %p
      %a{"data-reveal-id" => "mapModal", href: ""}
        %img{src: "https://a.tiles.mapbox.com/v3/foursquare.map-ikj05elx/15/9649/12317.png"}/
      %br/
      %a{"data-reveal-id" => "mapModal", href: ""} View Map
    %p= @venue.address
  / End Sidebar